import os
import json
import requests
from datetime import datetime
from dotenv import load_dotenv

# Load variables from .env
load_dotenv()

NOTION_TOKEN = os.getenv("NOTION_TOKEN")
DATABASE_ID = os.getenv("NOTION_DATABASE_ID")


HEADERS = {
    "Authorization": f"Bearer {NOTION_TOKEN}",
    "Content-Type": "application/json",
    "Notion-Version": "2022-06-28"
}


def format_date(due_string):
    """Forces Drexel dates to 11:59 PM and locks them to EST timezone"""
    try:
        # 1. Grab the date part (e.g., 2/22/26)
        date_part = due_string.split(',')[0].strip()

        # 2. Convert to datetime object
        dt = datetime.strptime(date_part, "%m/%d/%y")

        # 3. Create the ISO string with the Philly (EST) offset appended (-05:00)
        # This tells Notion: "This is 11:59 PM in Philly, don't shift it!"
        iso_local = f"{dt.year}-{dt.month:02d}-{dt.day:02d}T23:59:00-05:00"

        return iso_local
    except Exception as e:
        print(f"⚠️ Date Parsing Error: {e}")
        return None

        return dt.isoformat()
    except Exception as e:
        print(f"⚠️ Date Parsing Error: {e} on string '{due_string}'")
        return None


def create_notion_page(course, assignment, due_string):
    url = "https://api.notion.com/v1/pages"
    iso_date = format_date(due_string)

    # Debug line to confirm the 11:59 PM fix
    print(f"DEBUG: Processing [{course}] {assignment} -> Time: {iso_date}")

    payload = {
        "parent": {"database_id": DATABASE_ID},
        "properties": {
            "title": {
                "title": [{"text": {"content": assignment}}]
            },
            "Class": {
                # FIXED: Using 'select' for the single Select property type
                "select": {"name": course}
            }
        }
    }

    # Add the date if it parsed successfully
    if iso_date:
        payload["properties"]["Date"] = {"date": {"start": iso_date}}

    response = requests.post(url, json=payload, headers=HEADERS)

    if response.status_code != 200:
        print(f"❌ Notion Error {response.status_code}: {response.json().get('message')}")
        print(f"   Details: {response.json()}")

    return response.status_code


if __name__ == "__main__":
    try:
        # Load the data generated by your scraper
        with open('blackboard_data.json', 'r') as f:
            assignments = json.load(f)

        print(f"🔄 Syncing {len(assignments)} items to Notion...")

        success_count = 0
        for item in assignments:
            status = create_notion_page(item['course'], item['assignment'], item['due'])
            if status == 200:
                print(f"🚀 Synced: {item['assignment']}")
                success_count += 1

        print(f"\n✅ Success! Synced {success_count}/{len(assignments)} items.")

    except FileNotFoundError:
        print("❌ Error: blackboard_data.json not found. Run scraper.py first!")